CREATE TABLE IF NOT EXISTS migrations (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 migration VARCHAR(190) NOT NULL UNIQUE,
 batch INT UNSIGNED NOT NULL,
 executed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NULL,
 event VARCHAR(190) NOT NULL,
 ip_address VARCHAR(45) NULL,
 metadata JSON NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_audit_event_created(event,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
