-- ERASED CMS integrated MVP schema
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(190) NOT NULL DEFAULT '' AFTER email;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(40) NOT NULL DEFAULT 'author' AFTER password_hash;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(64) NULL AFTER role;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER totp_secret;
ALTER TABLE content ADD COLUMN IF NOT EXISTS author_id INT UNSIGNED NULL AFTER featured_media_id;
ALTER TABLE content ADD COLUMN IF NOT EXISTS category VARCHAR(190) NOT NULL DEFAULT '' AFTER author_id;
ALTER TABLE content ADD COLUMN IF NOT EXISTS tags TEXT NULL AFTER category;
ALTER TABLE content ADD COLUMN IF NOT EXISTS access_level VARCHAR(40) NOT NULL DEFAULT 'public' AFTER tags;
ALTER TABLE content ADD COLUMN IF NOT EXISTS publish_at DATETIME NULL AFTER access_level;
ALTER TABLE content ADD COLUMN IF NOT EXISTS language_code VARCHAR(12) NOT NULL DEFAULT 'en' AFTER publish_at;
ALTER TABLE content ADD COLUMN IF NOT EXISTS canonical_url VARCHAR(500) NOT NULL DEFAULT '' AFTER language_code;
ALTER TABLE content ADD COLUMN IF NOT EXISTS seo_title VARCHAR(255) NOT NULL DEFAULT '' AFTER canonical_url;
ALTER TABLE content ADD COLUMN IF NOT EXISTS seo_description TEXT NULL AFTER seo_title;
CREATE TABLE IF NOT EXISTS comments (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, content_id INT UNSIGNED NOT NULL, author_name VARCHAR(190) NOT NULL,
 author_email VARCHAR(190) NOT NULL, body TEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(content_id), INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS revisions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, content_id INT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL,
 body LONGTEXT NOT NULL, editor_id INT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(content_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS languages (
 code VARCHAR(12) PRIMARY KEY, name VARCHAR(100) NOT NULL, native_name VARCHAR(100) NOT NULL,
 is_default TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, is_rtl TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE languages ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER is_default;
UPDATE languages SET is_active = is_enabled WHERE is_enabled IS NOT NULL;
INSERT IGNORE INTO languages(code,name,native_name,is_default,is_active,is_rtl) VALUES
 ('en','English','English',1,1,0),('no','Norwegian','Norsk',0,1,0),('lt','Lithuanian','Lietuvių',0,1,0);
CREATE TABLE IF NOT EXISTS translations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, content_id INT UNSIGNED NOT NULL, language_code VARCHAR(12) NOT NULL,
 title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, excerpt TEXT NULL, body LONGTEXT NOT NULL,
 UNIQUE KEY uniq_content_lang(content_id,language_code), UNIQUE KEY uniq_lang_slug(language_code,slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS membership_plans (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL UNIQUE,
 price_minor INT NOT NULL DEFAULT 0, currency VARCHAR(8) NOT NULL DEFAULT 'NOK', interval_name VARCHAR(30) NOT NULL DEFAULT 'month',
 is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE membership_plans ADD COLUMN IF NOT EXISTS interval_name VARCHAR(30) NOT NULL DEFAULT 'month' AFTER currency;
UPDATE membership_plans SET interval_name = billing_interval WHERE billing_interval IS NOT NULL;
CREATE TABLE IF NOT EXISTS memberships (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, plan_id INT UNSIGNED NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'active', starts_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ends_at DATETIME NULL,
 provider VARCHAR(50) NOT NULL DEFAULT 'manual', provider_reference VARCHAR(190) NOT NULL DEFAULT '', INDEX(user_id), INDEX(plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payment_transactions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, provider VARCHAR(50) NOT NULL,
 provider_reference VARCHAR(190) NOT NULL DEFAULT '', amount_minor INT NOT NULL DEFAULT 0, currency VARCHAR(8) NOT NULL DEFAULT 'NOK',
 status VARCHAR(30) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS provider_reference VARCHAR(190) NOT NULL DEFAULT '' AFTER provider;
UPDATE payment_transactions SET provider_reference = provider_transaction_id WHERE provider_reference = '' AND provider_transaction_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS packages (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, package_type VARCHAR(30) NOT NULL, slug VARCHAR(190) NOT NULL,
 name VARCHAR(190) NOT NULL, version VARCHAR(40) NOT NULL DEFAULT '1.0.0', enabled TINYINT(1) NOT NULL DEFAULT 0,
 manifest LONGTEXT NULL, installed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uniq_package(package_type,slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS redirects (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_path VARCHAR(500) NOT NULL UNIQUE, target_path VARCHAR(500) NOT NULL,
 status_code SMALLINT NOT NULL DEFAULT 301, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL, ip_address VARCHAR(64) NOT NULL,
 successful TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(email), INDEX(ip_address), INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, action VARCHAR(190) NOT NULL,
 details LONGTEXT NULL, ip_address VARCHAR(64) NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
