CREATE TABLE IF NOT EXISTS example_notes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    note VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
